import Foundation

struct Idiom {
    let text: String
    let pinyin: String
    let meaning: String
}

enum Idioms {
    static let list: [Idiom] = [
        .init(text: "持之以恒", pinyin: "chí zhī yǐ héng", meaning: "长久坚持下去，永不放弃"),
        .init(text: "自强不息", pinyin: "zì qiáng bù xī", meaning: "自觉地努力向上，永不松懈"),
        .init(text: "厚积薄发", pinyin: "hòu jī bó fā", meaning: "大量积累后从容释放，终成大器"),
        .init(text: "水滴石穿", pinyin: "shuǐ dī shí chuān", meaning: "力量虽小，坚持可成大事"),
        .init(text: "磨杵成针", pinyin: "mó chǔ chéng zhēn", meaning: "只要有毅力，再难的事也能成功"),
        .init(text: "卧薪尝胆", pinyin: "wò xīn cháng dǎn", meaning: "刻苦自励，发愤图强"),
        .init(text: "破釜沉舟", pinyin: "pò fǔ chén zhōu", meaning: "下定决心，不留退路"),
        .init(text: "百炼成钢", pinyin: "bǎi liàn chéng gāng", meaning: "经过千锤百炼，成为坚强的人"),
        .init(text: "志在千里", pinyin: "zhì zài qiān lǐ", meaning: "形容志向远大，老当益壮"),
        .init(text: "大器晚成", pinyin: "dà qì wǎn chéng", meaning: "担当重任者多需长期磨炼"),
        .init(text: "闻鸡起舞", pinyin: "wén jī qǐ wǔ", meaning: "有志之士及时奋发努力"),
        .init(text: "悬梁刺股", pinyin: "xuán liáng cì gǔ", meaning: "形容学习刻苦，废寝忘食"),
        .init(text: "凿壁偷光", pinyin: "záo bì tōu guāng", meaning: "家境贫寒仍刻苦读书"),
        .init(text: "手不释卷", pinyin: "shǒu bù shì juàn", meaning: "勤奋好学，书本不离手"),
        .init(text: "全力以赴", pinyin: "quán lì yǐ fù", meaning: "把全部力量都投入进去"),
        .init(text: "精益求精", pinyin: "jīng yì qiú jīng", meaning: "已经很好了，还要求更好"),
        .init(text: "一鸣惊人", pinyin: "yī míng jīng rén", meaning: "平时默默无闻，一下子做出惊人成绩"),
        .init(text: "一飞冲天", pinyin: "yī fēi chōng tiān", meaning: "一下子冲上高空，比喻骤然得志"),
        .init(text: "鹏程万里", pinyin: "péng chéng wàn lǐ", meaning: "比喻前程远大"),
        .init(text: "扶摇直上", pinyin: "fú yáo zhí shàng", meaning: "乘风急速上升，比喻仕途得意"),
        .init(text: "白手起家", pinyin: "bái shǒu qǐ jiā", meaning: "在毫无基础条件下艰苦创业"),
        .init(text: "发愤图强", pinyin: "fā fèn tú qiáng", meaning: "下定决心，努力谋求强盛"),
        .init(text: "奋发图强", pinyin: "fèn fā tú qiáng", meaning: "振作精神，努力自强"),
        .init(text: "力争上游", pinyin: "lì zhēng shàng yóu", meaning: "努力奋斗，争取先进再先进"),
        .init(text: "再接再厉", pinyin: "zài jiē zài lì", meaning: "一次又一次地加倍努力"),
        .init(text: "勇往直前", pinyin: "yǒng wǎng zhí qián", meaning: "不怕困难，一直向前"),
        .init(text: "披荆斩棘", pinyin: "pī jīng zhǎn jí", meaning: "扫除前进中的一切困难和障碍"),
        .init(text: "乘风破浪", pinyin: "chéng fēng pò làng", meaning: "志向远大，不畏艰险，奋勇前进"),
        .init(text: "排除万难", pinyin: "pái chú wàn nán", meaning: "扫除重重障碍，克服各种困难"),
        .init(text: "迎难而上", pinyin: "yíng nán ér shàng", meaning: "明知困难，却迎头去克服"),
        .init(text: "百折不挠", pinyin: "bǎi zhé bù náo", meaning: "无论受多少挫折都不退缩"),
        .init(text: "不屈不挠", pinyin: "bù qū bù náo", meaning: "在困难面前绝不低头屈服"),
        .init(text: "坚韧不拔", pinyin: "jiān rèn bù bá", meaning: "意志坚定顽强，不可动摇"),
        .init(text: "锲而不舍", pinyin: "qiè ér bù shě", meaning: "坚持雕刻不放弃，比喻有恒心"),
        .init(text: "绳锯木断", pinyin: "shéng jù mù duàn", meaning: "力量虽小，坚持下去事情就会成功"),
        .init(text: "聚沙成塔", pinyin: "jù shā chéng tǎ", meaning: "聚细沙成宝塔，积少成多"),
        .init(text: "积少成多", pinyin: "jī shǎo chéng duō", meaning: "一点一滴地积累，就会从少变多"),
        .init(text: "集腋成裘", pinyin: "jí yè chéng qiú", meaning: "聚集细微之物可成大器"),
        .init(text: "有志竟成", pinyin: "yǒu zhì jìng chéng", meaning: "有志向的人，做事终会成功"),
        .init(text: "天道酬勤", pinyin: "tiān dào chóu qín", meaning: "上天会厚报勤奋的人"),
        .init(text: "勤能补拙", pinyin: "qín néng bǔ zhuō", meaning: "勤奋可以弥补天资的不足"),
        .init(text: "学无止境", pinyin: "xué wú zhǐ jìng", meaning: "学业永远没有尽头"),
        .init(text: "学以致用", pinyin: "xué yǐ zhì yòng", meaning: "为了实际应用而学习"),
        .init(text: "温故知新", pinyin: "wēn gù zhī xīn", meaning: "温习旧知识，获得新的理解与体会"),
        .init(text: "融会贯通", pinyin: "róng huì guàn tōng", meaning: "把各方面的知识融合贯穿，透彻理解"),
        .init(text: "触类旁通", pinyin: "chù lèi páng tōng", meaning: "掌握规律，推知同类的其他问题"),
        .init(text: "举一反三", pinyin: "jǔ yī fǎn sān", meaning: "从一件事情类推而知道其他许多事情"),
        .init(text: "开卷有益", pinyin: "kāi juàn yǒu yì", meaning: "只要读书，总有好处"),
        .init(text: "业精于勤", pinyin: "yè jīng yú qín", meaning: "学业的精深在于勤奋"),
        .init(text: "只争朝夕", pinyin: "zhǐ zhēng zhāo xī", meaning: "抓紧时间，力争在最短时间内达到目的"),
        .init(text: "时不我待", pinyin: "shí bù wǒ dài", meaning: "时间不会等人，要抓紧每一刻"),
        .init(text: "分秒必争", pinyin: "fēn miǎo bì zhēng", meaning: "一分一秒也不放过，抓紧时间"),
        .init(text: "事在人为", pinyin: "shì zài rén wéi", meaning: "事情的成败取决于人的努力"),
        .init(text: "人定胜天", pinyin: "rén dìng shèng tiān", meaning: "人的智慧和力量能够战胜自然"),
        .init(text: "当机立断", pinyin: "dāng jī lì duàn", meaning: "抓住时机，立刻作出决断"),
        .init(text: "知难而进", pinyin: "zhī nán ér jìn", meaning: "明知困难，却迎着困难上"),
        .init(text: "愈挫愈勇", pinyin: "yù cuò yù yǒng", meaning: "经历挫折越多，越加勇敢"),
        .init(text: "重整旗鼓", pinyin: "chóng zhěng qí gǔ", meaning: "失败之后，重新集合力量再干"),
        .init(text: "东山再起", pinyin: "dōng shān zài qǐ", meaning: "失势之后，再度出任要职施展才干"),
        .init(text: "卷土重来", pinyin: "juǎn tǔ chóng lái", meaning: "失败后重新恢复势力再来"),
        .init(text: "绝处逢生", pinyin: "jué chù féng shēng", meaning: "在走投无路的情况下找到生路"),
        .init(text: "柳暗花明", pinyin: "liǔ àn huā míng", meaning: "困境中出现新的转机"),
        .init(text: "峰回路转", pinyin: "fēng huí lù zhuǎn", meaning: "事情出现转机，局面焕然一新"),
        .init(text: "苦尽甘来", pinyin: "kǔ jìn gān lái", meaning: "艰苦的日子过完，美好的日子来到了"),
        .init(text: "玉汝于成", pinyin: "yù rǔ yú chéng", meaning: "艰难困苦的磨砺，能使人走向成功"),
        .init(text: "千磨万击", pinyin: "qiān mó wàn jī", meaning: "经受无数磨难打击，反而更加坚强"),
        .init(text: "傲雪凌霜", pinyin: "ào xuě líng shuāng", meaning: "不畏严寒，逆境中不屈不挠"),
        .init(text: "松柏之志", pinyin: "sōng bǎi zhī zhì", meaning: "坚贞不移的志向"),
        .init(text: "鸿鹄之志", pinyin: "hóng hú zhī zhì", meaning: "像天鹅一样翱翔高空的远大志向"),
        .init(text: "壮志凌云", pinyin: "zhuàng zhì líng yún", meaning: "理想宏伟远大，直上云霄"),
        .init(text: "胸怀大志", pinyin: "xiōng huái dà zhì", meaning: "心中有远大的抱负"),
        .init(text: "雄心壮志", pinyin: "xióng xīn zhuàng zhì", meaning: "伟大的理想和宏伟的志愿"),
        .init(text: "志存高远", pinyin: "zhì cún gāo yuǎn", meaning: "追求远大的理想和抱负"),
        .init(text: "登高望远", pinyin: "dēng gāo wàng yuǎn", meaning: "站得高，看得远"),
        .init(text: "高瞻远瞩", pinyin: "gāo zhān yuǎn zhǔ", meaning: "站得高看得远，眼光远大"),
        .init(text: "深谋远虑", pinyin: "shēn móu yuǎn lǜ", meaning: "计划周密，考虑长远"),
        .init(text: "运筹帷幄", pinyin: "yùn chóu wéi wò", meaning: "在后方决定作战策略，稳操全局"),
        .init(text: "胸有成竹", pinyin: "xiōng yǒu chéng zhú", meaning: "做事之前已有通盘考虑与把握"),
        .init(text: "未雨绸缪", pinyin: "wèi yǔ chóu móu", meaning: "事先做好准备工作"),
        .init(text: "有备无患", pinyin: "yǒu bèi wú huàn", meaning: "事先有准备，就可以避免祸患"),
        .init(text: "实事求是", pinyin: "shí shì qiú shì", meaning: "按照事物的实际情况办事"),
        .init(text: "脚踏实地", pinyin: "jiǎo tà shí dì", meaning: "做事踏实认真，不浮夸"),
        .init(text: "兢兢业业", pinyin: "jīng jīng yè yè", meaning: "小心谨慎，认真踏实"),
        .init(text: "任劳任怨", pinyin: "rèn láo rèn yuàn", meaning: "不怕辛苦，不怕埋怨"),
        .init(text: "见贤思齐", pinyin: "jiàn xián sī qí", meaning: "见到贤能的人就想向他看齐"),
        .init(text: "取长补短", pinyin: "qǔ cháng bǔ duàn", meaning: "吸取别人的长处，弥补自己的不足"),
        .init(text: "择善而从", pinyin: "zé shàn ér cóng", meaning: "选择好的去遵循和学习"),
        .init(text: "虚怀若谷", pinyin: "xū huái ruò gǔ", meaning: "胸怀像山谷一样深广，十分谦虚"),
        .init(text: "海纳百川", pinyin: "hǎi nà bǎi chuān", meaning: "胸怀宽广，能包容万物"),
        .init(text: "有容乃大", pinyin: "yǒu róng nǎi dà", meaning: "能包容一切，才成就其大"),
        .init(text: "上善若水", pinyin: "shàng shàn ruò shuǐ", meaning: "最高境界的善行，像水的品性一样"),
        .init(text: "饮水思源", pinyin: "yǐn shuǐ sī yuán", meaning: "喝水不忘挖井人，不忘根本"),
        .init(text: "感恩图报", pinyin: "gǎn ēn tú bào", meaning: "感激别人的恩情，并想办法回报"),
        .init(text: "推己及人", pinyin: "tuī jǐ jí rén", meaning: "设身处地为别人着想"),
        .init(text: "雪中送炭", pinyin: "xuě zhōng sòng tàn", meaning: "在别人急需时给予及时的帮助"),
        .init(text: "众人拾柴", pinyin: "zhòng rén shí chái", meaning: "人多力量大，团结就是力量"),
        .init(text: "同舟共济", pinyin: "tóng zhōu gòng jì", meaning: "团结互助，共渡难关"),
        .init(text: "众志成城", pinyin: "zhòng zhì chéng chéng", meaning: "万众一心，像坚固的城墙一样不可摧"),
        .init(text: "继往开来", pinyin: "jì wǎng kāi lái", meaning: "继承前人事业，开辟未来道路"),
        .init(text: "薪火相传", pinyin: "xīn huǒ xiāng chuán", meaning: "学问与技艺代代相传，永不熄灭"),
        .init(text: "周而复始", pinyin: "zhōu ér fù shǐ", meaning: "不断循环，坚持往复终有所成"),
        .init(text: "水到渠成", pinyin: "shuǐ dào qú chéng", meaning: "条件成熟，事情自然会成功"),
        .init(text: "瓜熟蒂落", pinyin: "guā shú dì luò", meaning: "时机成熟，事情自然成功"),
        .init(text: "功不唐捐", pinyin: "gōng bù táng juān", meaning: "所有的努力都不会白费")
    ]
}
